version: '3.3'
services:
  app:
    build:
      context: ./operations-es6
      dockerfile: Dockerfile
    ports:
      - "80:80"
  backend: 
    build: 
      context: ./operations-backend
      dockerfile: Dockerfile