version: "3.3"

services:
  operations-management:
    build:
      context: .
      dockerfile: Dockerfile
      labels: [FOO=BAR]
    healthcheck:
      test: curl -f http://localhost:8080/health || exit 1
      interval: 30s
      retries: 7
    ports:
      - "8080:8080"

